import './globals.css'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Google Clone App',
  description: 'Generated by Next js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
       className='relative min-h-screen'>
        {children}

        <Footer/>
       </body>
    </html>
  )
}
